### ISSUE TITLE
Request ShareThis 8.x-2.x-dev for PHP7

### ISSUE THREAD

**Issue by Quevin** [uwmweb/uwmcms#205]
re: https://www.drupal.org/project/sharethis/releases/8.x-2.x-dev @briantschu 

Seems to be working on Dev - https://huddle.cmsdev.uwmedicine.org/admin/config/services/sharethis 

But not on Stage
- https://huddle.cmsstage.uwmedicine.org/admin/config/services/sharethis

**Comment by chrisbeargroup** [comment]
What is the status on this? This is a blocker for some Tasks we need to complete. 
Thank you.

**Comment by briantschu** [comment]
Hey @chrisbeargroup and @Quevin sorry I missed this! The dev version of the module is now deployed to dev and stage. Looks like we need to switch Dev over to PHP7, too :)
