### ISSUE TITLE
Disallow robots for "The Huddle"

### ISSUE THREAD

**Issue by Quevin** [uwmweb/uwmcms#57]
Hi @briantschu , "The Huddle" would like to disallow robots from crawling and indexing their site. Would you be able to do this for specific multi-sites?
re: https://github.com/uwmweb/uwmcms/blob/develop/docroot/robots.txt

Thank you

**Comment by briantschu** [comment]
Hi @Quevin it seems like the best way to do this is with the [RobotsTxt module](https://www.drupal.org/project/robotstxt) per Acquia's Documentation "[Serving alternate robots.txt from a multisite](https://docs.acquia.com/articles/serving-alternate-robotstxt-files-multisite)".

I'll get that added in.
