### ISSUE TITLE
Install Google Tag Manager module

### ISSUE THREAD

**Issue by rlhawk** [uwmweb/uwmcms#70]
The Google Tag Manager module only has a development release for Drupal 8, but based on the comments from people who know Drupal well in the ["Port Google Tag Manager to D8" issue](https://www.drupal.org/node/2445983), I feel comfortable using it. If you agree, please add it to the project.

**Comment by briantschu** [comment]
Thanks, Rick. I initially overlooked the benefit of this plugin -- preventing the tag from loading for admin users. Thanks for doing the initial research. If we run into any issues we can revert to adding the container via the template and implement IP filters on the GTM/GA side if needed.

I'll add it!

**Comment by rlhawk** [comment]
Cool, thanks.
